version: '3'
services:
  azure-vote-back:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: azure-vote-back
    environment:
      HOST: "0.0.0.0"
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: myacr20250503.azurecr.io/azure-vote-front:v1
    #image: azure-vote-front:v1
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
      APPINSIGHTS_CONNECTION_STRING: "InstrumentationKey=f4246f7d-6e5c-487f-b322-e9d9c8555400;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=d4d1a781-c29a-4171-afbc-616a7ab98c15"
    ports:
        - "8080:80"
